version: '3.7'

services:

    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        environment:
            BACKEND: backend
            WAIT_HOSTS: db:27017

    backend:
        container_name: backend
        build: ./backend
        expose:
            - 8000
        environment:
            DB_USERNAME: user
            DB_PASSWORD: admin123
            DB_HOST: facemash_db
            DB_DATABASE: test
            PORT: 8000
            WAIT_HOSTS: facemash_db:27017
        volumes: 
            - "./imgs:/app/src/public/imgs:ro"

    db:
        container_name: facemash_db
        build: ./mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: admin123
        ports:
            - "27017:27017"
