version: '3.7'

services:

    frontend:
        build: ./frontend
        depends_on:
            - db
            - backend
        links:
            - backend
        ports:
            - "3000:3000"
        environment:
            WAIT_HOSTS: db:27017

    backend:
        build: ./backend
        depends_on:
            - db
        links:
            - db
        expose:
            - 8000
        environment:
            WAIT_HOSTS: db:27017

    db:
        container_name: db
        build: ./mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: admin123
        ports:
            - "27017:27017"
