version: '3.7'

services:

    web-app:
        build: ./code
        depends_on:
            - db
        links:
            - db
        ports:
            - "5000:5000"

    db:
        image: mongo
        expose:
            - "27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: admin123

        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        ports:
            - '27017:27017'
