version: '3.7'

services:
    web_app:
        build: ./code
        depends_on:
            - db
        links:
            - db
        ports:
            - "5000:5000"
        environment:
            WAIT_HOSTS: db:27017

    db:
        container_name: db
        build: ./mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: admin123
        ports:
            - "27017:27017"
