---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  database-host: database-service

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-initdb-script
data: 
  initdb-script.js: |
    db.createUser({
        user: "{{ .Values.database.username }}",
        pwd: "{{ .Values.database.password }}",
        roles: [{
          role: "readWrite",
          db: "test"
        }]
    });
    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
data:
  minio-host: minio-service