---
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
data:
  mongo_initdb_root_username: {{ .Values.database.rootUsername | b64enc }}
  mongo_initdb_root_password: {{ .Values.database.rootPassword | b64enc }}
  username: {{ .Values.database.username | b64enc }}
  password: {{ .Values.database.password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
data:
  minio_access_key: {{ .Values.minio.access_key | b64enc }}
  minio_secret_key: {{ .Values.minio.secret_key | b64enc }}