apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  database-host: database-service

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-initdb-script
data:
  initdb-script.js: |
    db.getSiblingDB('test');
    db.createUser({
        user: "user",
        pwd: "admin123",
        roles: ["readWrite"]
    });
    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
data:
  minio-host: minio-service