apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: facemash-db
spec:
  serviceName: database-service
  selector:
    matchLabels:
      app: facemash-db
  template:
    metadata:
      labels:
        app: facemash-db
    spec:
      containers:
      - name: facemash-db
        image: mongo:latest
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: mongo_initdb_root_username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-credentials
                key: mongo_initdb_root_password
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d/
            name: mongo-initdb-script
        ports:
          - containerPort: 27017
      volumes:
        - name: mongo-initdb-script
          configMap:
            name: mongo-initdb-script
            items:
            - key: initdb-script.js
              path: initdb-script.js
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  type: LoadBalancer
  selector:
    app: facemash-db
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30005