apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
data:
  mongo_initdb_root_username: cm9vdA==
  mongo_initdb_root_password: YWRtaW4xMjM=
  username: dXNlcg==
  password: YWRtaW4xMjM=